Repository WildCodeSchool/lyon-js-sept21-p2-g1-front, pull requests merged in 2021-11, with the labels that each got.

#25 Rating
  package-lock.json
  src/.DS_Store
  src/assets/parkingRating.jpg
  src/assets/undergroundpark.jpg
  src/components/ApiRating.jsx
  src/components/RatingStar.jsx
  src/pages/Rating.jsx
Labels: Ready for prod, Fixed - Ready for prod

#26 Rating
  src/pages/Rating.jsx
Labels: Ready for validation

#22 Maps
  .DS_Store
  .env.sample
  .eslintrc.json
  .gitignore
  package-lock.json
  package.json
  public/.DS_Store
  public/car-park.png
  public/carUser.png
  src/.DS_Store
  src/App.jsx
  src/assets/.DS_Store
  src/assets/iconCar.png
  src/assets/icon_car.svg
  src/components/Btn.jsx
  src/components/Maps.jsx
  src/components/Navbar.jsx
  src/components/SearchFields.jsx
  src/index.js
  src/pages/Map.jsx
  src/pages/SearchMap.jsx
  src/search.css
  src/serviceWorker.js
Labels: Conflicts, Fixed - Ready for prod

#28 Maps
  .DS_Store
  .eslintrc.json
  package-lock.json
  package.json
  public/.DS_Store
  public/car-park.png
  public/car-park2.png
  public/grandLyon.jpeg
  public/iconCarShare.png
  public/iconHandi.png
  public/iconHeight.png
  public/iconOpen.png
  public/iconParking.png
  public/iconPrice.png
  public/icons8-temps.gif
  src/.DS_Store
  src/App.jsx
  src/assets/.DS_Store
  src/assets/cardCity/aeroport.jpg
  src/assets/cardCity/pardieu.jpeg
  src/assets/cardCity/perrache.jpg
  src/assets/iconOpen.gif
  src/assets/phone.png
  src/assets/smartphone.png
  src/components/Background.jsx
  src/components/LegendMaps.jsx
  src/components/Maps.jsx
  src/components/Navbar.jsx
  src/components/Phone.jsx
  src/components/Search.jsx
  src/contexts/LoadingMapsContext.jsx
  src/index.css
  src/pages/Home.jsx
  src/pages/Home1.jsx
  src/pages/Map.jsx
  src/search.css
  tailwind.config.js
  yarn.lock
Labels: Ready for prod

#31 Maps
  .DS_Store
  .eslintrc.json
  package-lock.json
  public/.DS_Store
  public/car-Spot.png
  public/iconWaze.png
  src/.DS_Store
  src/assets/.DS_Store
  src/components/ApiRating.jsx
  src/components/CardCity.jsx
  src/components/Maps.jsx
  src/pages/Home.jsx
  src/pages/Home1.jsx
  src/search.css
  src/serviceWorker.js
  tailwind.config.js
Labels: WIP

#32 add the share page with form
  .gitignore
  package-lock.json
  package.json
  src/.DS_Store
  src/assets/.DS_Store
  src/assets/carParkFull.jpg
  src/assets/gps.png
  src/components/Navbar.jsx
  src/pages/Share.jsx
  src/share.css
  why-kei-8e2gal_GIE8-unsplash (1).jpg
Labels: Ready for prod, WIP

#36 Rating
  .DS_Store
  package-lock.json
  src/App.jsx
  src/components/RatingStar.jsx
  src/pages/ApiRating.jsx
  src/pages/Rating.jsx
  yarn.lock
Labels: Fixed - Ready for prod

#34 About us
  .DS_Store
  package-lock.json
  package.json
  public/.DS_Store
  public/car-park.png
  public/favicon.ico
  public/logo192.png
  public/logo512.png
  src/.DS_Store
  src/assets/.DS_Store
  src/assets/Cat1.jpg
  src/assets/Cat2.jpg
  src/assets/Cat3.jpg
  src/assets/Pegase.JPG
  src/components/Maps.jsx
  src/pages/AboutUs.jsx
  yarn.lock
Labels: Ready for prod
